apiVersion: v2
name: n8n
version: 0.11.2
appVersion: 0.237.0
type: application

description: "A Kubernetes Helm chart for n8n a free and open fair-code licensed node based Workflow Automation Tool. Easily automate tasks across different services."
home: https://github.com/8gears/n8n-helm-chart
icon: https://avatars1.githubusercontent.com/u/45487711?s=200&v=4
keywords:
  - Workflow Automation
  - Workflow
  - iPaaS
  - integration-framework
  - low-code-plattform
  - low-code
sources:
  - https://github.com/n8n-io/n8n
  - https://n8n.io/
  - https://github.com/8gears/n8n-helm-chart
maintainers:
  - name: Vadim Bauer
  - name: nmaas-platform
    email: nmaas-dev@lists.geant.org
    url: https://wiki.geant.org/display/NMAAS/NMaaS+Home
dependencies:
  - name: redis
    version: 17.2.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: postgresql
    version: 11.9.13
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: nmaas-bastion-ng
    version: 3.0.1
    repository: https://artifactory.software.geant.org/artifactory/nmaas-helm-stable-local
    condition: nmaas-bastion-ng.enabled